title: 'Feeling Good '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7992831
  brandStrength: 0.875
  rhythmicContrast: 0.4139785
  brandColors:
    - '#ffffff'
    - '#767676'
    - '#000000'
    - '#38c833'
    - '#aeaeae'
  lightness: 1
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: MindBodyfit
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1129032
layout_spectrum: 1
