name: MindBodyfit
favicon: null
layout_spectrum: 0.5892441277392209
typography_spectrum: 0.2840440212748945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#767676'
    - '#000000'
    - '#38c833'
    - '#aeaeae'
  brandStrength: 0.875
  lightness: 0.9879781021736562
  saturation: 0.375
  rhythmicContrast: 0.9819732951000333
purpose: []
